### ISSUE TITLE
display_np_arrays_as_images in (ported) einops tutorial missing

### ISSUE THREAD

**Issue by kochuyt** [arviz-devs/xarray-einstats#52]
I installed `xarray-einstats` from `conda-forge` and tried to reproduce `einops tutorial (ported)` from the [documentation](https://einstats.python.arviz.org/en/stable/tutorials/einops-basics-port.html)

This posed several challenges as it was not clear from the information in the documentation where to find

- `utils` module for importing the `display_np_arrays_as_images` function from
- `einops-image.zarr` file containing the batch of images usied in the tutorial

After digging around in this repository I managed to find the necessary files way down in the `docs / source / tutorials` folder

Maybe it is worth to add some explanation to this tutorial where / how to get those particular files onto your system (without having to do a full development from the github repository ;)

**Comment by kochuyt** [comment]
By the way, I love `xarray-einstats`!
It makes working with `xarray` much more enjoyable (and understandable for those of us having a hard time thinking in 4+ dimensions)

**Comment by OriolAbril** [comment]
Thanks for the feedback!

I am currently working on DataArray accessors for einops in #51, so I'll address this there. I think I'll move `display_np_arrays_as_images` to the tutorial module which contains functions only to be used for xarray-einstats docs and tests. And add instructions on how to download the zarr file from the browser; that is, paste `https://github.com/arviz-devs/xarray-einstats/tree/main/docs/source/tutorials/einops-image.zarr` into https://download-directory.github.io, uncompress and rename.

**Comment by OriolAbril** [comment]
Here is how the page will look like once the PR is merged: https://xarray-einstats--51.org.readthedocs.build/en/51/tutorials/einops-basics-port.html

**Comment by kochuyt** [comment]
That looks good to me, my friend 🙂
