### ISSUE TITLE
Many tests fail

### ISSUE THREAD

**Issue by yurivict** [arviz-devs/xarray-einstats#55]
[log](https://people.freebsd.org/~yuri/xarray-einstats-0.6.0-test.log)

Version: 0.6.0
Python-3.9
FreeBSD 13.2

**Comment by OriolAbril** [comment]
How have you installed the library? Are all [dependencies needed for testing](https://einstats.python.arviz.org/en/latest/contributing/how_to.html#running-the-test-suite-locally) installed? What versions of xarray, numpy, scipy, einops, numba are installed? 

All I can see in the log are error messages that end up in `E           ImportError: tlz.curry` which give me no information.
